#ifndef SRC_ZCL_ZCL_CUSTOM_ATTR_H_
#define SRC_ZCL_ZCL_CUSTOM_ATTR_H_

#define ZCL_ATTRID_BASIC_PRODUCT_LABEL  0x000E

#define ZCL_CUSTOM_ATTRID_SWITCH_MODEL  0xF002

enum {
    ZCL_CUSTOM_SWITCH_TYPE_LIGHT_CONTROL = 0x03,
    ZCL_CUSTOM_SWITCH_TYPE_MAXNUM
};

#define DEFAULT_MOVE_RATE                       100


#endif /* SRC_ZCL_ZCL_CUSTOM_ATTR_H_ */
